### ISSUE TITLE
Discontinuidad en la fuerza de Lennard-Jones

### ISSUE THREAD

**Issue by cerisola** [Tatotavella/molec_dyn#6]
En la version actual de la fuerza (y potencial) de Lennard-Jones, aunque correctos esta el problema que la fuerza es discontinua en el punto de truncamiento, como se puede ver en los gráficos.

Por lo que se había hablado en clase con Guillermo, esta discontinuidad puede traer problemas y por lo tanto en principio habría que, en cambio de directamente truncar el potencial, hacer una interpolación polinomial en entre r = 2.5 y r = 3.0, tal que el potencial y su primer derivada sean continuas y vayan a cero suavemente.

![fall](https://user-images.githubusercontent.com/16444945/27295283-befe1caa-54f2-11e7-97d6-6e3902b1f4af.png)

![fdiscont](https://user-images.githubusercontent.com/16444945/27295288-c5aac508-54f2-11e7-9c8e-aebce5db0029.png)

**Comment by Tatotavella** [comment]
Respecto a esto tengo una duda también sobre la interpolación que hablabamos cuando evaluabamos la fuerza. La tabla como esta implementada en make_table no evalua a f en 0 (que me parece correcto). Ahora bien para la implementacion si necesito interpolar con el punto anterior y actual eso generaria un problema en el caso de que una particula esté a esa distancia. Es cierto que el primer valor de delta r es rara vez tomado, pero como para pensar y ver que hacemos. Actualmente no hice una interpolacion y solo evaluo en el punto siguiente de la tabla

**Comment by cerisola** [comment]
Con el commit 7097b0cf4014aacae4456edfa46d37511895f5c0 de @ldlongo el problema parece estar corregido, como se muestra en la figura. Así que marco el issue como resuelto.

![fallcont](https://user-images.githubusercontent.com/16444945/27390705-577b67c2-5678-11e7-8fbd-a4df3fb80480.png)
