### ISSUE TITLE
Cambio en la aridad de eval_f

### ISSUE THREAD

**Issue by Tatotavella** [Tatotavella/molec_dyn#7]
Tuve que cambiar la aridad de la función eval_f ya que necesitaba el valor de dr para encontrar el índice correcto en la tabla.  
Antes estaba esta:  
`int eval_f(struct part *molec, long int N, double L, double *tabla);`  
Y ahora puse la siguiente  
`int eval_f(struct part *molec, long int N, double L, double *tabla, int numpoints);`

**Comment by cerisola** [comment]
Me parece que esta bien. Como parece no haber quejas lo cierro.
